In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
ord("a")

97

In [4]:
vid = cv2.VideoCapture(r"D:\movies\Charlie (2015) DVDRip - 1CD - x264 - AAC - Esub - Chaps - DrC Release.mkv")

In [4]:
vid = cv2.VideoCapture(r"D:\movies\Charlie (2015) DVDRip - 1CD - x264 - AAC - Esub - Chaps - DrC Release.mkv")
while True:
    su, img=vid.read()
    if su==False:
        break
    cv2.imshow("Video", img)
    if cv2.waitKey(1) & 255 ==ord("c"):
        break
cv2.destroyAllWindows()

In [ ]:
vid = cv2.VideoCapture(0)

c = np.ones(shape=(300,300), dtype='uint8')*255
d = np.zeros(shape=(300,300), dtype='uint8')
count=0
while True:
    su, Img=vid.read()
    if su == False:
        break
    b,g,r = cv2.split(Img)
    d = np.zeros(b.shape, dtype='uint8')
    cv2.imshow("video1",cv2.merge([b,d,d]))
    cv2.imshow("video2",cv2.merge([d,g,d]))
    cv2.imshow("vide03",cv2.merge([d,d,r]))
    #cv2.imshow("video",Img)
    cv2.imwrite(r"C:\Users\Erik\Documents\Innomatics assignments\innom practicing\deep learning\images\Img{}.jpg".format(count),Img)
    count+=1

    
    if cv2.waitKey(1) & 255== ord("c"):
        break
cv2.destroyAllWindows()

In [4]:
black = np.zeros((300, 300, 3), dtype=np.uint8)

# Draw a rectangle on the black image
cv2.rectangle(black, (50, 50), (150, 100), (0, 255, 0), -10)

# Display the black image with the rectangle
cv2.imshow("rectangle", black)

# Wait for any key press
cv2.waitKey(0)

# Close the OpenCV window
cv2.destroyAllWindows()

In [4]:
vid = cv2.VideoCapture(0)
while True:
    su, img=vid.read()
    if su==False:
        break
    cv2.imshow("Video", img)
    if cv2.waitKey(1) & 255 ==ord("q"):
        break
cv2.destroyAllWindows()

In [4]:
black = np.zeros((200,200,3),dtype=np.uint8)
cv2.namedWindow("pic", cv2.WINDOW_FREERATIO)


cv2.imshow("pic", black)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
black = np.zeros((200,200,3),dtype=np.uint8)
cv2.namedWindow("pic", cv2.WINDOW_FREERATIO)

cv2.line(black,(100,0), (100,200), (0,0,255),10)

cv2.imshow("pic", black)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
black = np.zeros((200,200,3),dtype=np.uint8)
cv2.namedWindow("pic", cv2.WINDOW_FREERATIO)

cv2.rectangle(black,(100,100), (150,200),(0,0,255),10)

cv2.imshow("pic", black)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
black = np.zeros((200,200,3),dtype=np.uint8)
cv2.namedWindow("elipse", cv2.WINDOW_FREERATIO)
cv2.ellipse(black,(100,100),(20,10), 0,0,360,(0,255,0),-1)
cv2.ellipse(black,(70,70),(20,10), 0,0,360,(0,255,0),1)
cv2.imshow("elipse", black)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
black = np.zeros((200,200,3),dtype=np.uint8)
cv2.namedWindow("text", cv2.WINDOW_FREERATIO)

cv2.putText(black,"welcom to opencv", (10, 50), cv2.FONT_ITALIC, 0.5, (255,0,0), 1)

cv2.imshow("text", black)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
vid = cv2.VideoCapture(0)

count=0
while True:
    suc, img=vid.read()
    print(img.shape)
    cv2.rectangle(img, (50,50), (350,400),(0,255,0), 1)
    cv2.putText(img,"Naga",(50,50), cv2.FONT_ITALIC,1,(0,0,255),1)
    cv2.imshow("Naga", img)
    cv2.imwrite(r"C:\Users\Erik\Documents\Innomatics assignments\innom practicing\deep learning\images\Img{}.jpg".format(count),img)
    count+=1
    
    if cv2.waitKey(1) & 255 ==ord("q"):
        break
        
cv2.destroyAllWindows()

(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 640, 3)
(480, 

In [4]:
import cv2
import numpy as np

# Create a black image
img = np.zeros((300, 300, 3), dtype=np.uint8)

cv2.namedWindow("b",cv2.WINDOW_FREERATIO)
# Draw the ellipse on the image
cv2.putText(img,"Welcome to Opeancv",(10,100),cv2.FONT_ITALIC,0.5,(0,0,255),1)

# Display the image with the ellipse
cv2.imshow("r",img)

# Wait for any key press
cv2.waitKey(0)

# Close the OpenCV window
cv2.destroyAllWindows()

In [ ]:
vid = cv2.VideoCapture(0)

c = np.ones(shape=(300,300), dtype='uint8')*255
d = np.zeros(shape=(300,300), dtype='uint8')
count=0
while True:
    su, Img=vid.read()
    if su == False:
        break
    b,g,r = cv2.split(Img)
    d = np.zeros(b.shape, dtype='uint8')
    cv2.imshow("video1",cv2.merge([b,d,d]))
    cv2.imshow("video2",cv2.merge([d,g,d]))
    cv2.imshow("vide03",cv2.merge([d,d,r]))
    #cv2.imshow("video",Img)
    cv2.imwrite(r"C:\Users\Erik\Documents\Innomatics assignments\innom practicing\deep learning\images\Img{}.jpg".format(count),Img)
    count+=1

    
    if cv2.waitKey(1) & 255== ord("c"):
        break
cv2.destroyAllWindows()

In [4]:
vid = cv2.VideoCapture(0)
count=0
while True:
    su, Img=vid.read()
    cv2.putText(Img,"naga",(10,100),cv2.FONT_ITALIC,0.5,(0,0,255),1)
    cv2.rectangle(black, (50, 50), (150, 100), (0, 255, 0), 1)
    cv2.imwrite(r"C:\Users\Erik\Documents\Innomatics assignments\innom practicing\deep learning\images\Img{}.jpg".format(count),Img)
    count+=1

    
    if cv2.waitKey(1) & 255== ord("q"):
        break
cv2.destroyAllWindows()

NameError: name 'img' is not defined

In [ ]:
for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

In [11]:
vid = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
while True:
    suc, img=vid.read()
    if not suc :
        break
    
    cv2.putText(img,"Naga",(50,50), cv2.FONT_ITALIC,1,(0,0,255),1)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

    cv2.imshow("image", img)
    #cv2.imwrite(r"C:\Users\Erik\Documents\Innomatics assignments\innom practicing\deep learning\images\Img{}.jpg".format(count),img)
    #count+=1
    
    if cv2.waitKey(1) & 255 ==ord("q"):
        break
        
cv2.destroyAllWindows()

## 19/03/2024

In [24]:
Tx = 0
Ty = 0
t = np.array([[1,0,100],[0,1,50]],dtype= np.float32)

In [25]:
t

array([[  1.,   0., 100.],
       [  0.,   1.,  50.]], dtype=float32)

In [39]:
img = cv2.imread(r"C:\Users\Erik\Pictures\edit_pic_1.jpg")

In [10]:
img.shape

(1080, 1080, 3)

In [26]:
t_img =cv2.warpAffine(img, t, (1080, 1080,))

In [44]:
cv2.namedWindow("tr",cv2.WINDOW_FREERATIO)

cv2.imshow("tr",t_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
1080/2

540.0

In [40]:
ro_mat = cv2.getRotationMatrix2D((1080/2,1080/2), 180,1)

In [41]:
ro_img  =cv2.warpAffine(img, ro_mat, (1080, 1080,))

In [5]:
cv2.namedWindow("ro",cv2.WINDOW_FREERATIO)

cv2.imshow("ro",ro_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'ro_img' is not defined

In [54]:
cv2.resize(img, None,fx=0.2,fy=0.2).shape

(216, 216, 3)

In [56]:
cv2.imshow("o", cv2.resize(img, None,fx=0.2,fy=0.2))


cv2.waitKey(0)
cv2.destroyAllWindows()

In [60]:
up = cv2.pyrUp(img)

In [62]:
cv2.pyrUp(img).shape

(2160, 2160, 3)

In [63]:
cv2.pyrDown(img).shape

(540, 540, 3)

In [64]:
cv2.imshow("o", cv2.resize(up, None,fx=0.2,fy=0.2))


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.pyrDown()
cv2.pyrUp()

## 21/03/2024

In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread(r"C:\Users\Erik\Pictures\new_pic.jpg")

In [3]:
c_i = img[35:174, 33:143]

In [4]:
cv2.imshow("oi", img)
cv2.imshow("ci",c_i)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
cv2.imshow("oi", img)
cv2.imshow("higer intensity", cv2.add(img,np.full(img.shape,100, dtype=np.uint8)))
cv2.imshow("lower intensity", cv2.subtract(img,np.full(img.shape,100, dtype=np.uint8)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:

cv2.add(img,np.full(img.shape,100, dtype=np.uint8))

array([[[149, 178, 209],
        [149, 178, 209],
        [149, 178, 209],
        ...,
        [102, 102, 102],
        [109, 103, 108],
        [112, 106, 111]],

       [[149, 178, 209],
        [149, 178, 209],
        [149, 178, 209],
        ...,
        [100, 100, 104],
        [100, 100, 106],
        [103, 101, 107]],

       [[150, 178, 209],
        [150, 178, 209],
        [150, 178, 209],
        ...,
        [192, 201, 210],
        [191, 197, 208],
        [190, 196, 207]],

       ...,

       [[116, 142, 136],
        [116, 142, 136],
        [116, 142, 136],
        ...,
        [101, 102, 100],
        [101, 102, 100],
        [101, 102, 100]],

       [[116, 142, 136],
        [116, 142, 136],
        [116, 142, 136],
        ...,
        [101, 102, 100],
        [101, 102, 100],
        [101, 102, 100]],

       [[116, 142, 136],
        [116, 142, 136],
        [116, 142, 136],
        ...,
        [101, 102, 100],
        [101, 102, 100],
        [101, 102, 100]]

In [3]:
b_i = np.zeros((500,500), np.uint8)

In [4]:
cv2.rectangle(b_i,(150,150), (250,250),(255),-1)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [5]:
cv2.imshow("lower intensity", b_i)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
b_i1 = np.zeros((500,500), np.uint8)
cv2.circle(b_i1,(100,100),100,(255),-1)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [7]:
ands = cv2.bitwise_and(b_i, b_i1)
ors=cv2.bitwise_or(b_i, b_i)
xors = cv2.bitwise_and(b_i, b_i1)
cv2.imshow("1", b_i1)
cv2.imshow("2", b_i)
cv2.imshow("and", ands)
cv2.imshow("or", ors)
v2.imshow("xor", xors)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
ands = cv2.bitwise_and(b_i, b_i1)
ors=cv2.bitwise_or(b_i, b_i)
xors = cv2.bitwise_and(b_i, b_i1)
cv2.imshow("and", ands)
cv2.imshow("or", ors)
cv2.imshow("xor", xors)
cv2.waitKey(0)
cv2.destroyAllWindows()