In [1]:
import cv2

In [2]:
face=cv2.CascadeClassifier(r"C:\Users\Erik\Downloads\haarcascade_frontalface_alt.xml")
# img = cv2.imread(r"C:\Users\Erik\Pictures\KARUNA.jpg",0)

In [3]:
vid=cv2.VideoCapture(0)
face_data= []
count=0
while True:
    suc, img = vid.read()
    print(suc)
    gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    arr=face.detectMultiScale(gray_img)
    for x,y,w,h in arr:
        crop_img=gray_img[y-10:y+h+10, x-10:x+w+10]
        
    cv2.imshow("crop",crop_img)
    cv2.imshow('gray',gray_img)
    

    if count%20==0:
        face_data.append(cv2.resize(crop_img,(100,100)))
        
    if cv2.waitKey(1) == ord('q'):
        break
cv2.destroyAllWindows()

True


NameError: name 'crop_img' is not defined

In [8]:
arr

array([[284, 210, 193, 193]])

In [9]:
arr.shape

(1, 4)

In [10]:
len(face_data)

145

In [11]:
face_data

[array([[210, 212, 210, ..., 122, 126, 131],
        [211, 211, 209, ...,  85, 104, 107],
        [212, 212, 211, ...,  75,  88, 101],
        ...,
        [ 94,  96, 102, ..., 123, 122, 118],
        [ 95,  94,  97, ..., 135, 128, 133],
        [ 97,  93,  99, ..., 129, 149, 141]], dtype=uint8),
 array([[210, 210, 211, ..., 132, 149, 168],
        [213, 213, 213, ..., 121, 129, 128],
        [212, 212, 213, ...,  81,  96, 104],
        ...,
        [126, 117, 118, ..., 141, 126, 128],
        [116, 107, 116, ..., 138, 135, 144],
        [101, 108, 111, ..., 139, 145, 149]], dtype=uint8),
 array([[212, 212, 211, ..., 123, 141, 154],
        [211, 212, 211, ..., 118, 122, 124],
        [213, 212, 212, ...,  84, 103, 109],
        ...,
        [120, 120, 117, ..., 137, 133, 130],
        [114, 115, 117, ..., 135, 139, 149],
        [105, 108, 112, ..., 137, 142, 153]], dtype=uint8),
 array([[211, 213, 212, ...,  93, 112, 125],
        [210, 210, 212, ...,  74,  80,  97],
        [212, 21

In [ ]:
data.reshape()

In [12]:
import numpy as np
data = np.asarray(face_data)

In [13]:
data.reshape(data.shape[0],-1)

array([[210, 212, 210, ..., 129, 149, 141],
       [210, 210, 211, ..., 139, 145, 149],
       [212, 212, 211, ..., 137, 142, 153],
       ...,
       [ 75,  69,  62, ..., 140, 136, 134],
       [214, 107,  77, ..., 131, 135, 134],
       [114,  76,  73, ..., 132, 135, 137]], dtype=uint8)

In [14]:
data.reshape(data.shape[0],-1).shape

(145, 10000)

In [15]:
len(data)

145

In [16]:
import numpy as np

In [17]:
np.save(r"C:\Users\Erik\Documents\Innomatics assignments\innom practicing\deep learning\open cv\open cv coding\images\naga.npy", data.reshape(data.shape[0],-1))

In [ ]:
import os

In [ ]:
os.listdir(r" path")

In [ ]:
final_data = []
count=0
diction = {}
for faces in os.listdir(r"open cv/images"):
    final_data.append(np.conacatenate([np.load(r"open cv/images/naga.npy", format(faces)),np.full(128,1),count))]axis=1)

    diction.update({faces:count})
    count+=1

In [ ]:
final_data

In [11]:
face=cv2.CascadeClassifier(r"C:\Users\Erik\Downloads\haarcascade_frontalface_alt.xml")

In [3]:
vid=cv2.VideoCapture(0)
face_data= []
count=0
while True:
    suc, img = vid.read()
    print(suc)
    gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    arr=face.detectMultiScale(gray_img)
    for x,y,w,h in arr:
        crop_img=gray_img[y-10:y+h+10, x-10:x+w+10]
        cv2.imshow("crop",crop_img)
    
    cv2.imshow('gray',gray_img)
    

    if count%20==0:
        face_data.append(cv2.resize(crop_img,(100,100)))
        
    if cv2.waitKey(1) & 255 == ord('q'):
        break
cv2.destroyAllWindows()

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
